from core.yaml_config import YamlConfig, BUILDS_DIR
from core.analyzer import Analyzer
from core.simulation_runner import SimulationRunner

import argparse
import os
import sys

def parse_args():
    parser = argparse.ArgumentParser(
        description='Run simulation and/or analysis based on a YAML configuration.'
    )
    parser.add_argument(
        '--analysis-only',
        action='store_true',
        help='It only runs the step of analyzing the .dump and .txt files generated by the simulation, given the generated directory. It does not run the simulation.'
    )
    parser.add_argument(
        '--config',
        help='Configuration file for your friction simulation in YAML format'
    )
    parser.add_argument(
        '--dir',
        nargs='?',
        default=None,
        help='Dump folder (analysis-only) or output directory (full run)'
    )
    return parser.parse_args()

def load_config(yaml_file: str, output_dir: str) -> YamlConfig:
    config = YamlConfig(yaml_file, output_dir)
    if not config.load_config():
        sys.exit('Error: failed to load YAML configuration.')
    return config

def run_analysis_mode(yaml_file: str, dump_folder: str) -> None:
    config = load_config(yaml_file, BUILDS_DIR)
    config.analysis_output_path = os.path.join(dump_folder, 'analysis')
    analyzer = Analyzer(yaml_config=config, dump_folder=dump_folder)

    if analyzer.run_analysis():
        print('Analysis completed successfully.')
        print(f'Results available at: {config.get_analysis_output_path()}')
        sys.exit(0)
    sys.exit('Error: analysis failed.')

def run_full_mode(yaml_file: str, output_dir: str) -> None:
    # Load configuration and render simulation template
    config = load_config(yaml_file, output_dir)
    if not config.render_template():
        sys.exit('Error: failed to render simulation template.')
    simulation_path = config.get_simulation_file_path()
    runner = SimulationRunner(simulation_path)
    analyzer = Analyzer(yaml_config=config)

    # Execute simulation
    if not runner.execute():
        sys.exit('Error: simulation failed.')
    print('Simulation completed successfully.')

    # Execute analysis
    if not analyzer.run_analysis():
        sys.exit('Error: analysis failed.')
    print('Analysis completed successfully.')
    print(f'\nResults available at: {config.get_analysis_output_path()}')
    sys.exit(0)

def main():
    args = parse_args()
    
    if args.analysis_only:
        if not args.dir:
            sys.exit('Error: in --analysis-only mode you must specify a dump folder (--dir).')
        run_analysis_mode(args.config, args.dir)
    else:
        output_dir = args.dir or BUILDS_DIR
        run_full_mode(args.config, output_dir)

if __name__ == '__main__':
    main()